package net.pinae.caliperapp

const val MEASURE_REQUEST_CODE = 213
const val SIGN_IN_REQUEST_CODE = 9001
const val PERMISSIONS_REQUEST_CODE = 34
const val GOOGLE_FIT_PERMISSIONS_REQUEST_CODE = 9213

const val MEASUREMENT_POSITION = "MEASUREMENT_POSITION"